In [2]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten
import numpy as np
import os
import cv2

In [17]:
img_width, img_height = 25, 25
input_shape = (img_width, img_height, 1)
batch_size = 10
no_epochs = 25
no_classes = 2
validation_split = 0.2
verbosity = 1

In [28]:
def load_data(data_type:str='train', class_name:str='hot_dog'):
    instances = []
    classes = []
    for filepath in os.listdir('data/{}/{}'.format(data_type, class_name)):
        resized_img = cv2.imread('data/{}/{}/{}'.format(data_type, class_name, format(filepath)), 0)
        resized_img = cv2.resize(resized_img, (img_width, img_height))
        instances.append(resized_img)
        classes.append(0 if class_name == 'not_hot_dog' else 1)
    return instances, classes


In [31]:
def create_model():
    model = Sequential()
    model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
    model.add(Conv2D(8, kernel_size=(3, 3), activation='relu'))
    model.add(Conv2D(12, kernel_size=(3, 3), activation='relu'))
    model.add(Flatten())
    model.add(Dense(256, activation='relu'))
    model.add(Dense(no_classes, activation='softmax'))
    return model

In [9]:
def compile_model(model):
    model.compile(loss=tensorflow.keras.losses.sparse_categorical_crossentropy,
                    optimizer=tensorflow.keras.optimizers.Adam(), metrics=['accuracy'])
    return model

In [10]:
def train_model(model, X_train, y_train):
    model.fit(X_train, y_train,
            batch_size=batch_size,
            epochs=no_epochs,
            verbose=verbosity,
            shuffle=True,
            validation_split=validation_split)
    return model

In [11]:
def test_model(model, X_test, y_test):
    score = model.evaluate(X_test, y_test, verbose=0)
    print('Test loss: {}/ Test accuracy: {}'.format(score[0], score[1]))
    return model

In [27]:
X_train_nh, y_train_nh = load_data(data_type='train', class_name='not_hot_dog')
X_train_h, y_train_h = load_data(data_type='train', class_name='hot_dog')
X_train = np.array(X_train_nh + X_train_h)
X_train = X_train.reshape((X_train.shape[0], img_width, img_height, 1))
y_train = np.array(y_train_nh + y_train_h)

8 136 131 ...  55  49  46]
 [138 137 134 ...  66  65  61]
 [136 136 135 ...  64  67  64]
 ...
 [ 85  79  73 ...   9   9   9]
 [ 79  80  77 ...   9   9   9]
 [ 72  79  79 ...   9   9   9]]
[[174 174 174 ...  45  19  23]
 [173 173 173 ...  67  31  22]
 [172 172 172 ... 126  90  57]
 ...
 [187 189 191 ...  17  18  19]
 [185 184 186 ...  18  21  23]
 [186 184 187 ...  18  23  26]]
[[ 95  96  96 ... 237 236 230]
 [ 93  94  94 ... 236 234 228]
 [ 93  92  91 ... 235 232 224]
 ...
 [159 162 142 ... 169 165 160]
 [154 158 151 ... 173 169 165]
 [150 158 163 ... 173 170 166]]
[[ 77  80  84 ...  12  12  12]
 [ 76  78  81 ...  12  13  13]
 [ 75  77  78 ...  12  12  13]
 ...
 [150 148 146 ...  72  67  64]
 [151 149 146 ...  70  66  63]
 [152 149 146 ...  70  66  63]]
[[ 6  6  6 ... 41 29 22]
 [ 6  6  6 ... 24 21 27]
 [ 8  8  7 ... 24 36 57]
 ...
 [25 25 25 ... 13 13 12]
 [29 30 30 ... 12 12 12]
 [34 34 35 ... 12 11 10]]
[[ 92  92  92 ... 201 202 205]
 [ 94  94  93 ... 202 203 206]
 [ 96  95  95 ... 

In [29]:
X_test_nh, y_test_nh = load_data(data_type='test', class_name='not_hot_dog')
X_test_h, y_test_h = load_data(data_type='test', class_name='hot_dog')
X_test = np.array(X_test_nh + X_test_h)
X_test = X_test.reshape((X_test.shape[0], img_width, img_height, 1))
y_test = np.array(y_test_nh + y_test_h)

In [32]:
model = create_model()
model = compile_model(model)
model = train_model(model, X_train, y_train)
model = test_model(model, X_test, y_test)

Epoch 1/25
40/40 [==============================] - 1s 20ms/step - loss: 31.9522 - accuracy: 0.5947 - val_loss: 1.8089 - val_accuracy: 0.4600
Epoch 2/25
40/40 [==============================] - 0s 12ms/step - loss: 0.4745 - accuracy: 0.8207 - val_loss: 2.3482 - val_accuracy: 0.3200
Epoch 3/25
40/40 [==============================] - 1s 14ms/step - loss: 0.0917 - accuracy: 0.9775 - val_loss: 2.2458 - val_accuracy: 0.4200
Epoch 4/25
40/40 [==============================] - 0s 12ms/step - loss: 0.0171 - accuracy: 0.9994 - val_loss: 2.8734 - val_accuracy: 0.4000
Epoch 5/25
40/40 [==============================] - 1s 13ms/step - loss: 0.0124 - accuracy: 0.9980 - val_loss: 3.0304 - val_accuracy: 0.4100
Epoch 6/25
40/40 [==============================] - 0s 12ms/step - loss: 0.0061 - accuracy: 1.0000 - val_loss: 3.2900 - val_accuracy: 0.4000
Epoch 7/25
40/40 [==============================] - 0s 12ms/step - loss: 0.0049 - accuracy: 1.0000 - val_loss: 3.5703 - val_accuracy: 0.3900
Epoch 8/25
4